### PR TITLE
fix AttributeError

### PR DESCRIPTION
**Pull request by simonLeary42**
Coldfront crashes when you try to approve an allocation change request with attribute changes.

Bug demonstrated by new regression tests: https://github.com/ubccr/coldfront/actions/runs/18820946912/job/53696360798?pr=855

```
Internal Server Error: /allocation/change-request/3/
Traceback (most recent call last):
  File "/srv/simon/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/srv/simon/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/simon/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/simon/venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/simon/venv/lib/python3.12/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/simon/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/simon/venv/lib/python3.12/site-packages/coldfront/core/allocation/views.py", line 1900, in post
    allocation_pk=attribute_change.allocation.pk,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AllocationAttributeChangeRequest' object has no attribute 'allocation'
```

you can find `AllocationAttributeChangeRequest` here: 

https://github.com/ubccr/coldfront/blob/a4b6b4c1d18535f61de5aa4bbfe509d7d8ca4b0f/coldfront/core/allocation/models.py#L720

Introduced in https://github.com/ubccr/coldfront/pull/675

### CODE REVIEW

**Comment by simonLeary42** [comment]
I also replaced usage of `status_id` with `status.name`, since it's more intuitive.

**Comment by simonLeary42** [comment]
The test I added doesn't actually cover this bug, it just seemed to be missing. More to come

**Review by aebruno — APPROVED** [review]
